[package]
name = "grow-a-robloxian-discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
serenity = "0.12.4"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
